import face from '../../../../notations/face';

export default {
  cases: [
    face.b.one,
    face.b.pri,
    face.b.two,
    face.b.any,
    face.d.one,
    face.d.pri,
    face.d.two,
    face.d.any,
    face.e.one,
    face.e.pri,
    face.e.two,
    face.e.any,
    face.f.one,
    face.f.pri,
    face.f.two,
    face.f.any,
    face.l.one,
    face.l.pri,
    face.l.two,
    face.l.any,
    face.m.one,
    face.m.pri,
    face.m.two,
    face.m.any,
    face.r.one,
    face.r.pri,
    face.r.two,
    face.r.any,
    face.s.one,
    face.s.pri,
    face.s.two,
    face.s.any,
    face.u.one,
    face.u.pri,
    face.u.two,
    face.u.any,
  ],
  name: 'face',
};
