import side from '../../../../notations/side';

export default {
  cases: [
    side.b.one,
    side.b.pri,
    side.b.two,
    side.b.any,
    side.d.one,
    side.d.pri,
    side.d.two,
    side.d.any,
    side.f.one,
    side.f.pri,
    side.f.two,
    side.f.any,
    side.l.one,
    side.l.pri,
    side.l.two,
    side.l.any,
    side.r.one,
    side.r.pri,
    side.r.two,
    side.r.any,
    side.u.one,
    side.u.pri,
    side.u.two,
    side.u.any,
  ],
  name: 'side',
};
